import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/component/Header';
import { User } from 'lucide-react';
import { UserProvider } from '@/context/userContext';
import { CategoryProvider } from '@/context/categoryContext';
import { SubCategoryProvider } from '@/context/subCategoryContext';
import { NewPlaceProvider } from '@/context/newPlaceContext';
import { TourProvider } from '@/context/tourContext';
import Footer from '@/component/common/Footer';




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function LocaleLayout({
  children,
  params
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider>
          <UserProvider>
            <TourProvider>
            <NewPlaceProvider>
            <CategoryProvider>
              <SubCategoryProvider>
                <Header />
                {children}
                <Footer/>
              </SubCategoryProvider>
            </CategoryProvider>
            </NewPlaceProvider>
            </TourProvider>
          </UserProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

